### ISSUE TITLE
odata-mock: $metadata endpoint is not working

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#117]
As part of the ODATA specification a [metadata](https://www.odata.org/documentation/odata-version-2-0/overview/#ServiceMetadataDocument) endpoint must be provided using path "basepath/$metadata".

On a local running instance of the odata-mock, calling "http://localhost:10000/odata/$metadata" the following exception is raised:
```
Error: Missing attribute value for attribute Type of element Property
    at new XMLAttribute (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLAttribute.js:13:15)
    at XMLElement.module.exports.XMLElement.attribute (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLElement.js:72:35)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:75:30)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:81:32)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:81:32)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLDocument.module.exports.XMLNode.element (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at Object.module.exports.create (/Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/node_modules/xmlbuilder/lib/index.js:22:16)
    at /Users/d061230/go/src/github.wdf.sap.corp/SAP-CP-Extension-Factory/application-mocks/marketing-mock/node_modules/n-odata-server/lib/base/metadata/metadata.js:83:46
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by obadrawi** [comment]
Removed everything in the models attribute in the boot_config.json except the ACL property because it's needed for n-odata-server to work but the others are referencing entities that don't exist
