### ISSUE TITLE
Disconnecting a Mock with odata-module enabled is failing

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#234]
Calling the disconnect button on a mock having the odata-module embedded will fail with:
```
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;statusCode&#39; of undefined<br>
at ServerResponse.res.send (/app/node_modules/@varkes/odata-mock/dist/server/routes.js:14:47)<br>
at disconnect (/app/node_modules/@varkes/api-server/dist/server/routes/connector.js:50:21)<br>
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br>
at next (/app/node_modules/express/lib/router/route.js:137:13)<br>
at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)<br>
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br>
at /app/node_modules/express/lib/router/index.js:281:22<br>
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)<br>
at next (/app/node_modules/express/lib/router/index.js:275:10)<br>
at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)<br>
at router (/app/node_modules/express/lib/router/index.js:47:12)<br>
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br>
at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)<br>
at /app/node_modules/express/lib/router/index.js:284:7<br>
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)<br>
at next (/app/node_modules/express/lib/router/index.js:275:10)<br>
at /app/node_modules/express-winston/index.js:364:9<br>
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br>
at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)<br>
at /app/node_modules/express/lib/router/index.js:284:7<br>
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)<br>
at next (/app/node_modules/express/lib/router/index.js:275:10)</pre> </body> </html> 
````

The odata-module is listening on the root api path and transform any error response and causes a null-pointer.

**Comment by a-thaler** [comment]
Fixed by removing relevant code part as it was useless
